apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ynthyb2bw-python
  janus-idp.io/tekton: ynthyb2bw-python
  backstage.io/kubernetes-id: ynthyb2bw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ynthyb2bw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
